name: Build & Test & Docs & Deploy

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  # Allows manual runs from the Actions tab
  workflow_dispatch:

# We need these permissions for GitHub Pages deployments.
permissions:
  contents: read      # Allows reading repository contents
  pages: write        # Allows publishing to GitHub Pages
  id-token: write     # Needed for OIDC authentication to Pages

# Prevent multiple deployments from clashing.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-test-docs-deploy:
    runs-on: ubuntu-latest

    # This sets the environment name (optional) and references the final page_url output
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name : Update npm
        run: npm update

      - name: Run tests
        run: npm test

      - name: Generate documentation
        run: npm run doc

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Documentation Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Display Deployed URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"